[MYSQL]
MYSQL_HOST = "mysql.railway.internal"
MYSQL_USER = "root"
MYSQL_PASSWORD = "kAfGOGEepZaJkWdmTJpTSniVKBxUFNJy"
MYSQL_DATABASE = "railway"
MYSQL_PORT = 3306

[EMAIL]
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USERNAME = ""
SMTP_PASSWORD = ""
FROM_EMAIL = "" 